export const ENLACES = {
  // --- TANDA 1 ---
  "safo-de-lesbos": "https://ciudadseva.com/autor/safo/poemas/",
  "li-bai": "https://circulodepoesia.com/2015/03/balada-de-las-estaciones-dossier-de-poesia-china/",
  "du-fu": "https://circulodepoesia.com/2015/03/balada-de-las-estaciones-dossier-de-poesia-china/",
  "rumi": "https://www.zendalibros.com/5-poemas-de-rumi/",
  "omar-jayam": "https://circulodepoesia.com/2013/01/poemas-de-omar-khayyam/",
  "dante-alighieri": "https://ciudadseva.com/autor/dante/poemas/",
  "francesco-petrarca": "https://ciudadseva.com/autor/francesco-petrarca/poemas/",
  "matsuo-basho": "https://circulodepoesia.com/2013/03/matsuo-bashou-y-el-origen-del-haiku/",
  "san-juan-de-la-cruz": "https://ciudadseva.com/autor/san-juan-de-la-cruz/poemas/",
  "sor-juana-ines-de-la-cruz": "https://www.culturagenial.com/es/poemas-de-sor-juana-ines-de-la-cruz/",

  // --- TANDA 2 ---
  "garcilaso-de-la-vega": "https://www.zendalibros.com/sonetos-de-garcilaso-de-la-vega/",
  "luis-de-gongora": "https://www.zendalibros.com/5-poemas-de-gongora/",
  "francisco-de-quevedo": "https://www.zendalibros.com/5-poemas-quevedo/",
  "william-shakespeare": "https://www.culturagenial.com/es/poemas-de-william-shakespeare/",
  "william-blake": "https://www.zendalibros.com/5-poemas-de-william-blake/",
  "friedrich-holderlin": "https://circulodepoesia.com/2011/05/albala-friedrich-holderlin/",
  "john-keats": "https://www.zendalibros.com/5-poemas-de-john-keats/",
  "giacomo-leopardi": "https://www.zendalibros.com/poemas-giacomo-leopardi/",
  "walt-whitman": "https://www.zendalibros.com/5-poemas-walt-whitman/",
  "emily-dickinson": "https://www.zendalibros.com/5-poemas-de-emily-dickinson-71-poemas/",

  // --- TANDA 3 ---
  "charles-baudelaire": "https://www.zendalibros.com/poemas-de-las-flores-del-mal-de-charles-baudelaire/",
  "arthur-rimbaud": "https://circulodepoesia.com/2016/10/poesia-francesa-arthur-rimbaud/",
  "stephane-mallarme": "https://materialdelectura.unam.mx/poesia-moderna/16-poesia-moderna-cat/64-027-stephane-mallarme",
  "rosalia-de-castro": "https://www.culturagenial.com/es/rosalia-de-castro-poemas/",
  "ruben-dario": "https://www.culturagenial.com/es/ruben-dario-poemas/",
  "antonio-machado": "https://www.culturagenial.com/es/antonio-machado-poemas/",
  "juan-ramon-jimenez": "https://materialdelectura.unam.mx/poesia-moderna/16-poesia-moderna-cat/331-181-juan-ramon-jimenez",
  "rainer-maria-rilke": "https://materialdelectura.unam.mx/poesia-moderna/16-poesia-moderna-cat/119-052-rainer-maria-rilke",
  "constantino-cavafis": "https://materialdelectura.unam.mx/poesia-moderna/16-poesia-moderna-cat/62-025-cavafis",
  "fernando-pessoa": "https://materialdelectura.unam.mx/poesia-moderna/16-poesia-moderna-cat/25-004-fernando-pessoa",

  // --- TANDA 4 ---
  "anna-ajmatova": "https://materialdelectura.unam.mx/poesia-moderna/16-poesia-moderna-cat/80-034-ana-ajmatova",
  "marina-tsvetaieva": "https://www.zendalibros.com/5-poemas-de-marina-tsvetaieva/",
  "t-s-eliot": "https://materialdelectura.unam.mx/poesia-moderna/16-poesia-moderna-cat/52-018-ts-eliot",
  "cesar-vallejo": "https://www.zendalibros.com/5-poemas-cesar-vallejo/",
  "vicente-huidobro": "https://materialdelectura.unam.mx/poesia-moderna/16-poesia-moderna-cat/104-043-vicente-huidobro",
  "federico-garcia-lorca": "https://www.culturagenial.com/es/poemas-esenciales-de-federico-garcia-lorca/",
  "pablo-neruda": "https://www.culturagenial.com/es/pablo-neruda-los-poemas-mas-populares/",
  "gabriela-mistral": "https://materialdelectura.unam.mx/poesia-moderna/16-poesia-moderna-cat/144-065-gabriela-mistral",
  "jorge-luis-borges": "https://www.culturagenial.com/es/borges-poemas/",
  "jose-lezama-lima": "https://materialdelectura.unam.mx/poesia-moderna/16-poesia-moderna-cat/26-005-jose-lezama-lima",

  // --- TANDA 5 ---
  "octavio-paz": "https://materialdelectura.unam.mx/poesia-moderna/16-poesia-moderna-cat/85-octavio-paz",
  "paul-celan": "https://circulodepoesia.com/2017/10/paul-celan-los-poemas-rumanos/",
  "wis-awa-szymborska": "https://www.zendalibros.com/5-poemas-de-wislawa-szymborska/",
  "alejandra-pizarnik": "https://materialdelectura.unam.mx/poesia-moderna/16-poesia-moderna-cat/194-093-alejandra-pizarnik",
  "sylvia-plath": "https://www.zendalibros.com/5-poemas-de-sylvia-plath-navona/",
  "allen-ginsberg": "https://www.zendalibros.com/5-poemas-allen-ginsberg/",
  "idea-vilarino": "https://materialdelectura.unam.mx/poesia-moderna/16-poesia-moderna-cat/308-153-idea-vilarino",
  "blanca-varela": "https://www.vallejoandcompany.com/2016/08/19/ese-viento-alevoso-de-la-memoria-13-poemas-de-blanca-varela/",
  "mahmud-darwish": "https://circulodepoesia.com/2023/11/poemas-de-mahmoud-darwish/",
  "olga-orozco": "https://circulodepoesia.com/2019/08/poesia-panhispanica-no-24-olga-orozco/",

  // --- TANDA 6 ---
  "virgilio": "https://circulodepoesia.com/2019/09/virgilio-a-2000-anos-de-su-muerte/",
  "horacio": "https://poeticas.es/?p=2723",
  "ovidio": "https://circulodepoesia.com/2019/08/ovidio-tristes/",
  "catulo": "https://poesiamaspoesia.com/75-poesia-mas-poesia-catulo/",
  "wang-wei": "https://poesiamaspoesia.com/228-poesia-mas-poesia-wang-wei/",
  "li-qingzhao": "https://poesiamaspoesia.com/253-poesia-mas-poesia-li-qingzhao/",
  "hafez": "https://circulodepoesia.com/2013/01/un-poema-de-hafiz/",
  "kabir": "http://amediavoz.com/kabir.htm",
  "mirabai": "https://institutodeindologia.es/index.php/articulos/literatura/558-poemas-mirabai",
  "jorge-manrique": "http://amediavoz.com/manrique.htm",

  // --- TANDA 7 ---
  "fray-luis-de-leon": "https://www.espoesia.com/poesia/fray-luis-de-leon-2/",
  "santa-teresa-de-jesus": "https://teresavila.com/poesias/",
  "john-donne": "http://amediavoz.com/donne.htm",
  "john-milton": "https://poetryalquimia.org/2024/12/09/7-poemas-de-john-milton/",
  "johann-wolfgang-von-goethe": "https://www.zendalibros.com/5-poemas-goethe/",
  "novalis": "https://trianarts.com/novalis-el-hombre-de-la-flor-azul/",
  "heinrich-heine": "https://www.zendalibros.com/5-poemas-de-heinrich-heine/",
  "victor-hugo": "https://www.zendalibros.com/plenitud-de-victor-hugo/",
  "gerard-de-nerval": "https://circulodepoesia.com/2016/01/gerard-de-nerval-el-desdichado/",
  "gustavo-adolfo-becquer": "https://www.culturagenial.com/es/rimas-de-gustavo-adolfo-becquer/",

  // --- TANDA 8 ---
  "paul-verlaine": "https://www.zendalibros.com/5-poemas-de-paul-verlaine/",
  "paul-valery": "https://materialdelectura.unam.mx/poesia-moderna/16-poesia-moderna-cat/24-003-paul-valery",
  "guillaume-apollinaire": "https://materialdelectura.unam.mx/poesia-moderna/16-poesia-moderna-cat/233-103-guillaume-apollinaire",
  "w-b-yeats": "https://www.zendalibros.com/5-poemas-de-he-extendido-mis-suenos-a-tus-pies-de-w-b-yeats/",
  "ezra-pound": "https://www.zendalibros.com/5-poemas-de-ezra-pound/",
  "wallace-stevens": "https://www.zendalibros.com/5-poemas-wallace-stevens/",
  "william-carlos-williams": "https://www.zendalibros.com/los-mejores-poemas-de-william-carlos-williams/",
  "e-e-cummings": "http://amediavoz.com/cummings.htm",
  "robert-frost": "https://www.zendalibros.com/5-poemas-de-intervalo-en-la-montana-de-robert-frost/",
  "giuseppe-ungaretti": "https://poetryalquimia.org/2023/02/10/11-poemas-de-giuseppe-ungaretti/",
  "eugenio-montale": "https://circulodepoesia.com/2018/11/eugenio-montale-huesos-de-sepia/",
  "osip-mandelshtam": "https://circulodepoesia.com/2018/09/el-ultimo-poema-de-osip-mandelshtam/",
  "vladimir-mayakovski": "https://circulodepoesia.com/2020/11/poesia-rusa-vladimir-mayakovski/",
  "czes-aw-mi-osz": "https://circulodepoesia.com/2018/08/un-poema-de-czeslaw-milosz/",
  "tomas-transtromer": "https://circulodepoesia.com/2012/06/dos-poemas-de-thomas-transtromer/",
  "yorgos-seferis": "https://circulodepoesia.com/2018/08/poema-para-leer-un-viernes-por-la-tarde-gymnopedia-de-giorgos-seferis/",
  "odysseas-elytis": "https://materialdelectura.unam.mx/poesia-moderna/16-poesia-moderna-cat/220-096-odysseas-elytis",
  "rabindranath-tagore": "https://www.elcopoylarueca.com/rabindranath-tagore-poemas/",
  "aime-cesaire": "https://circulodepoesia.com/2010/02/cinco-poemas-de-aime-cesaire/",
  "nazim-hikmet": "https://poetryalquimia.org/2022/01/15/14-poemas-de-nazim-hikmet/",
  "forough-farrojzad": "https://poetryalquimia.org/2023/12/28/7-poemas-de-forough-farrokhzad-%D9%81%D8%B1%D9%88%D8%BA-%D9%81%D8%B1%D8%AE%D8%B2%D8%A7%D8%AF/",
  "luis-cernuda": "https://materialdelectura.unam.mx/poesia-moderna/98-039-luis-cernuda",

  // --- TANDA 9 ---
  "vicente-aleixandre": "https://www.zendalibros.com/5-poemas-de-vicente-aleixandre/",
  "rafael-alberti": "https://www.zendalibros.com/5-poemas-rafael-alberti/",
  "miguel-hernandez": "https://www.zendalibros.com/5-poemas-miguel-hernandez/",
  "jose-marti": "https://www.culturagenial.com/es/jose-marti-poemas/",
  "delmira-agustini": "https://poetryalquimia.org/2018/10/24/11-poemas-de-delmira-agustini/",
  "alfonsina-storni": "https://www.culturagenial.com/es/poemas-esenciales-de-alfonsina-storni/",
  "nicanor-parra": "https://www.zendalibros.com/5-poemas-nicanor-parra/",
  "juan-gelman": "https://materialdelectura.unam.mx/poesia-moderna/16-poesia-moderna-cat/333-183-juan-gelman",
  "jose-emilio-pacheco": "https://circulodepoesia.com/2014/01/poemas-de-jose-emilio-pacheco/",
  "jaime-sabines": "https://trianarts.com/grandes-poetas-jaime-sabines/",
  "rosario-castellanos": "https://materialdelectura.unam.mx/poesia-moderna/123-053-rosario-castellanos",
  "nicolas-guillen": "https://cvc.cervantes.es/literatura/escritores/guillen/poemas/default.htm",
  "carlos-drummond-de-andrade": "https://materialdelectura.unam.mx/poesia-moderna/16-poesia-moderna-cat/107-045-carlos-drummond-de-andrade",
  "joao-cabral-de-melo-neto": "https://circulodepoesia.com/2020/07/100-anos-de-joao-cabral-de-melo-neto/",
  "charles-bukowski": "https://poetryalquimia.org/2018/08/16/10-poemas-de-charles-bukowski/",
  "mary-oliver": "https://poetryalquimia.org/2024/09/10/11-poemas-de-mary-oliver/",
  "langston-hughes": "https://circulodepoesia.com/2016/09/poesia-norteamericana-langston-hughes/",
  "elizabeth-bishop": "https://poetryalquimia.org/2022/02/08/11-poemas-de-elizabeth-bishop/",
  "dylan-thomas": "https://poetryalquimia.org/2017/10/27/poemas-de-dylan-thomas/",
  "w-h-auden": "https://circulodepoesia.com/2011/06/poetcast-musee-de-beaux-arts-por-w-h-auden/",
  "anne-carson": "https://poetryalquimia.org/2021/06/21/8-poemas-de-anne-carson/",
  "jose-angel-valente": "https://poesiamaspoesia.com/224-poesia-mas-poesia-jose-angel-valente/",
};
